-- Supprimer toutes les anciennes colonnes (y compris celles de la migration précédente si elle a été appliquée)
ALTER TABLE profiles_infos
DROP COLUMN IF EXISTS age,
DROP COLUMN IF EXISTS niveau_etudes,
DROP COLUMN IF EXISTS matieres_reussite,
DROP COLUMN IF EXISTS matieres_difficulte,
DROP COLUMN IF EXISTS pref_apprendre,
DROP COLUMN IF EXISTS prend_notes,
DROP COLUMN IF EXISTS utilise_resumes,
DROP COLUMN IF EXISTS travail_seul_groupe,
DROP COLUMN IF EXISTS etude_frequence,
DROP COLUMN IF EXISTS outils_apprentissage,
DROP COLUMN IF EXISTS comprehension_texte,
DROP COLUMN IF EXISTS reperer_mots_cles,
DROP COLUMN IF EXISTS reformuler_texte,
DROP COLUMN IF EXISTS planifier_reponse,
DROP COLUMN IF EXISTS erreurs_inattention,
DROP COLUMN IF EXISTS planning_etudes,
DROP COLUMN IF EXISTS heures_travail_ecole,
DROP COLUMN IF EXISTS difficulte_commencer,
DROP COLUMN IF EXISTS finir_travaux_delais,
DROP COLUMN IF EXISTS distraction_etudes,
DROP COLUMN IF EXISTS trouble_diagnostique,
DROP COLUMN IF EXISTS trouble_diagnostique_precision,
DROP COLUMN IF EXISTS plan_aide_scolaire,
DROP COLUMN IF EXISTS aime_apprendre,
DROP COLUMN IF EXISTS decouragement_travail,
DROP COLUMN IF EXISTS stress_examen,
DROP COLUMN IF EXISTS objectifs_etudes,
DROP COLUMN IF EXISTS recompense_objectif,
DROP COLUMN IF EXISTS question_1_reponse,
DROP COLUMN IF EXISTS question_2_reponse,
DROP COLUMN IF EXISTS question_3_reponse,
DROP COLUMN IF EXISTS question_4_reponse,
DROP COLUMN IF EXISTS question_5_reponse,
DROP COLUMN IF EXISTS question_6_reponse,
DROP COLUMN IF EXISTS question_7_reponse,
DROP COLUMN IF EXISTS question_8_reponse,
DROP COLUMN IF EXISTS question_9_reponse,
DROP COLUMN IF EXISTS question_10_reponse;

-- Ajouter les nouvelles colonnes avec les noms courts et descriptifs
ALTER TABLE profiles_infos
ADD COLUMN pref_apprendre_idee TEXT,
ADD COLUMN memoire_poesie TEXT,
ADD COLUMN resoudre_maths TEXT,
ADD COLUMN temps_libre_pref TEXT,
ADD COLUMN travail_groupe_role TEXT,
ADD COLUMN retenir_info TEXT,
ADD COLUMN pref_enseignant TEXT,
ADD COLUMN decouvrir_endroit TEXT,
ADD COLUMN reussir_definition TEXT,
ADD COLUMN souvenir_important TEXT;
