-- Supprimer les anciennes colonnes
ALTER TABLE profiles_infos
DROP COLUMN IF EXISTS age,
DROP COLUMN IF EXISTS niveau_etudes,
DROP COLUMN IF EXISTS matieres_reussite,
DROP COLUMN IF EXISTS matieres_difficulte,
DROP COLUMN IF EXISTS pref_apprendre,
DROP COLUMN IF EXISTS prend_notes,
DROP COLUMN IF EXISTS utilise_resumes,
DROP COLUMN IF EXISTS travail_seul_groupe,
DROP COLUMN IF EXISTS etude_frequence,
DROP COLUMN IF EXISTS outils_apprentissage,
DROP COLUMN IF EXISTS comprehension_texte,
DROP COLUMN IF EXISTS reperer_mots_cles,
DROP COLUMN IF EXISTS reformuler_texte,
DROP COLUMN IF EXISTS planifier_reponse,
DROP COLUMN IF EXISTS erreurs_inattention,
DROP COLUMN IF EXISTS planning_etudes,
DROP COLUMN IF EXISTS heures_travail_ecole,
DROP COLUMN IF EXISTS difficulte_commencer,
DROP COLUMN IF EXISTS finir_travaux_delais,
DROP COLUMN IF EXISTS difficulte_concentration,
DROP COLUMN IF EXISTS distraction_etudes,
DROP COLUMN IF EXISTS trouble_diagnostique,
DROP COLUMN IF EXISTS trouble_diagnostique_precision,
DROP COLUMN IF EXISTS plan_aide_scolaire,
DROP COLUMN IF EXISTS aime_apprendre,
DROP COLUMN IF EXISTS decouragement_travail,
DROP COLUMN IF EXISTS stress_examen,
DROP COLUMN IF EXISTS objectifs_etudes,
DROP COLUMN IF EXISTS recompense_objectif;

-- Ajouter les nouvelles colonnes
ALTER TABLE profiles_infos
ADD COLUMN question_1_reponse TEXT,
ADD COLUMN question_2_reponse TEXT,
ADD COLUMN question_3_reponse TEXT,
ADD COLUMN question_4_reponse TEXT,
ADD COLUMN question_5_reponse TEXT,
ADD COLUMN question_6_reponse TEXT,
ADD COLUMN question_7_reponse TEXT,
ADD COLUMN question_8_reponse TEXT,
ADD COLUMN question_9_reponse TEXT,
ADD COLUMN question_10_reponse TEXT;
