// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slgfyacikclvswsctfmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZ2Z5YWNpa2NsdnN3c2N0Zm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTU2MjUsImV4cCI6MjA2OTk5MTYyNX0.iPx8iwkgnD71elDkZdMJLWK4GG7KZFYlbIyE0KJGQ4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});